name: Continuous Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests & Lint on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Clippy (Linting)
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test --verbose

      - name: Run Code Coverage (Linux Only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Lcov
          bash <(curl -s https://codecov.io/bash) -f lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
